contracts:
  transparentProxies:
    Locking: "0x096Bd9a7a2e703670088C05035e23c7a9F428496"
    RariMineV3: "0xc633F65A1BEBD433DF12D9F3ac7aCF31b26Ca1E6"
  nonupgradable:
    RariToken: "0xFca59Cd816aB1eaD66534D82bc21E7515cE441CF"