contracts:
  AdminProxy: "0x80033c932904E077e55a6E43E5E9a796f34d2525"
  transparentProxies:
    RoyaltiesRegistry: "0xEa90CFad1b8e030B8Fd3E63D22074E0AEb8E0DCD"
    ExchangeV2: "0x9757F2d2b135150BBeb65308D4a91804107cd8D6"
  nonupgradable:
    ERC1155LazyMintTransferProxy: "0x75a8B7c0B22D973E0B46CfBD3e2f6566905AA79f"
    #ERC20TransferProxy: "0xb8e4526e0da700e9ef1f879af713d691f81507d8"
    ERC721LazyMintTransferProxy: "0xbb7829BFdD4b557EB944349b2E2c965446052497"
    #TransferProxy: "0x4fee7b061c97c9c496b01dbce9cdb10c02f0a0be"
